# Generated by Django 4.2.4 on 2023-09-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_rename_category_id_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='starts',
            field=models.DateTimeField(null=True),
        ),
    ]
