# Generated by Django 4.2.4 on 2023-09-21 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_profile_address_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='num_notifications',
            field=models.IntegerField(default=0),
        ),
    ]
