# Generated by Django 3.2.22 on 2023-10-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_todo_num_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
