# Generated by Django 3.2.22 on 2023-10-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_alter_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_notifications',
            field=models.BooleanField(default=False, verbose_name='Присылать уведомления'),
        ),
    ]
